services:
  traefik:
    image: "traefik:v2.9"
    init: true
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web-network

  website:
    image: "demo-site"
    init: true
    container_name: "demo-website"
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.website.rule=Host(`website.localhost`)"
      #- "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.test-compress.compress=true"
    networks:
      - web-network

  varnish:
    image: varnish:stable
    init: true
    container_name: "varnish"
    depends_on:
      - "website"
    volumes:
      - "./_config/varnish/default.vcl:/etc/varnish/default.vcl:ro"
    tmpfs:
      - /var/lib/varnish:exec
    networks:
      - web-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=web-network
      - traefik.constraint-label=web-network
      # SERVICE
      - traefik.http.services.varnish.loadbalancer.server.port=80
      - "traefik.http.routers.varnish.entrypoints=web"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"

networks:
  web-network:
    name: web-network
    driver: bridge
