services:
  traefik:
    image: "traefik:v2.9"
    init: true
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      # Enable gzip compression
      - "traefik.http.routers.traefik.middlewares=traefik-compress"
      - "traefik.http.middlewares.traefik-compress.compress=true"


    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web-network

  website:
    image: "demo-site"
    init: true
    container_name: "website"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`website.localhost`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.home.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.website.compress=true"
      - "traefik.http.routers.website.middlewares=website"

    networks:
      - web-network

networks:
  web-network:
    name: web-network
    driver: bridge